version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
    - '5432:5432'
    environment:
    - POSTGRES_DB=database_development
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: ["sh", "run.sh"]
    ports:
    - '8080:8080'
    volumes:
    - ./api:/code
    depends_on:
    - db
