version: '3.8'

services:
  db:
    image: postgres:11-alpine
    ports:
    - '5432:5432'
    environment:
    - POSTGRES_DB=database_development
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  web:
    build: .
    image: probono-api
    command: ["sh", "run.sh"]
    ports:
    - '3000:3000'
    volumes:
    - .:/code
    environment:
    - NODE_ENV=development
    - NODE_PATH=.
    - PORT=3000
    - SECRET=my-secret-key-api
    depends_on:
    - db
